name: 🐛 New Bug Report
description: Help Pulsar improve by filing a bug report
labels: ["bug", "triage"]
body:
- type: checkboxes
  id: initiative-check
  attributes:
    label: Thanks in advance for your bug report!
    description: "Please make sure you have done the following:"
    options:
      - label: Checked your issue is not in our list of [common issues](https://docs.pulsar-edit.dev/troubleshooting-pulsar/common-issues)?
        required: true
      - label: Reproduced issue in [safe mode](https://docs.pulsar-edit.dev/troubleshooting-pulsar/using-safe-mode)?
        required: true
      - label: Used the [debugging guide](https://docs.pulsar-edit.dev/troubleshooting-pulsar) to try to resolve the issue?
        required: true
      - label: Checked to make sure your issue does not already [exist](https://github.com/issues?q=sort%3Aupdated-desc+is%3Aissue+user%3Apulsar-edit)?
        required: true
      - label: Checked you are on the [latest release](https://pulsar-edit.dev/download/#latest-version)?
        required: true
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    placeholder: Tell us what happened!
  validations:
    required: true
- type: input
  id: pulsar-version
  attributes:
    label: Pulsar version
  validations:
    required: true
- type: dropdown
  id: os-info
  attributes:
    label: Which OS does this happen on?
    options:
      - 🐧 Debian based (Linux Mint, Ubuntu, etc.)
      - 🐧 Arch based (Manjaro, Garuda, etc.)
      - 🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)
      - 🐧 OpenSUSE based
      - 🍎 macOS
      - 🪟 Windows
      - ❓ Other(Please specify in the OS details field below)
  validations:
    required: true
- type: input
  id: os-version
  attributes:
    label: OS details
    placeholder: OS version, distribution etc.
  validations:
    required: true
- type: input
  id: package-type
  attributes:
    label: How did you install Pulsar? 
    placeholder: Website download (deb, rpm, appimage etc.), package repository etc.
  validations:
    required: false
- type: dropdown
  id: sys-info
  attributes:
    label: Which CPU architecture are you running this on?
    options:
      - x86_64/AMD64
      - Apple M-series
      - ARM64/AArch64
  validations:
    required: false
- type: textarea
  id: steps
  attributes:
    label: What steps are needed to reproduce this?
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  id: additional-context
  attributes:
    description: |
      "What other details can you provide?"
    label: "Additional Information:"
    placeholder: |
      Add any other information or screenshots relating to the bug here.
      If building from source please provide the commit hash here.
  validations:
    required: false
